### PR TITLE
Specified that margin comes from ggplot2

### PR DESCRIPTION
**Pull request by dgrtwo**
I learned this once the function stopped working after I loaded the randomForest package 😆

### CODE REVIEW

**Comment by dgrtwo** [comment]
Oh noooooo I put `ggplot2::margin = margin` instead of `margin = ggplot2::margin`. You should never have trusted me!

But related note: why does base_size affect margin, but isn't actually passed? Shouldn't there be a `base_size = base_size`?

**Comment by juliasilge** [comment]
@dgrtwo This PR wouldn't install but I fixed it; I think it works.

**Comment by juliasilge** [comment]
The `base_size`/margin thing is to nudge the title up a little bit; I copied that out of `theme_minimal()`.

**Comment by dgrtwo** [comment]
That makes sense but right now it's not changing the font size at all, I think you need to pass `base_size = base_size` to `theme_minimal()`

**Comment by juliasilge** [comment]
AAUGH, yep.

**Pull request merged**
